name: bb_sports
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  stylish_bottom_bar: ^1.1.1
  percent_indicator: ^4.2.5
  mockito: ^5.5.0
  build_runner: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/

  
